# Generated by Django 5.0.7 on 2024-11-13 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsintomas', models.DateField()),
                ('fiebre', models.BooleanField()),
                ('dolor_articulaciones', models.BooleanField()),
                ('dolor_detras_de_ojos', models.BooleanField()),
                ('dolor_muscular', models.BooleanField()),
                ('dolor_de_cabeza', models.BooleanField()),
                ('erupcion_cutanea', models.BooleanField()),
                ('nauseas_vomitos', models.BooleanField()),
                ('dolor_abdominal_intenso', models.BooleanField()),
                ('vomitos_persistentes', models.BooleanField(null=True)),
                ('sangrado_mucosas_y_encias', models.BooleanField(null=True)),
                ('somnolencia_irritabilidad', models.BooleanField(null=True)),
                ('decaimiento', models.BooleanField(null=True)),
                ('otros', models.TextField(blank=True, max_length=300, null=True)),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
                ('tiempo_deteccion', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesis_app.examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
